### ISSUE TITLE
env.reset( ) NotImplementedError

### ISSUE THREAD

**Issue by TIE666** [zfw1226/gym-unrealcv#23]
Hi,

I am trying to use unrealcv on my own research project, I got the demo random agent running, but once it connected to the server, there's an error that stops it from runnning anymore. Trace log as below:
```
Running docker-free env, pid:8020
Please wait for a while to launch env......
start /b  c:\users\tie\github\gym-unrealcv\gym_unrealcv\envs\UnrealEnv\RealisticRendering\RealisticRendering.exe
127.0.0.1
INFO:__init__:192:Got connection confirm: b'connected to RealisticRendering'
Traceback (most recent call last):
  File "random_agent.py", line 33, in <module>
    ob = env.reset()
  File "C:\Users\tie\anaconda3\envs\gym-unrealcv\lib\site-packages\gym\wrappers\time_limit.py", line 27, in reset
    return self.env.reset(**kwargs)
  File "C:\Users\tie\anaconda3\envs\gym-unrealcv\lib\site-packages\gym\core.py", line 74, in reset
    raise NotImplementedError
NotImplementedError
```
Does that mean I might need a different version of gym ?
I am using windows 10, with anaconda, but don't think that's related since the demo is already running.

Would be great if I could have some help here, appreciate the work.

**Comment by TIE666** [comment]
Oh, it was the gym version, for people who might experience the same, gym 0.19 is what you need to get it running.
