### ISSUE TITLE
textures path not found

### ISSUE THREAD

**Issue by iOkay** [zfw1226/gym-unrealcv#32]
work on branch v1.0 and windows 10
Python 3.11.6
`  Running setup.py develop for gym-unrealcv
Successfully installed contourpy-1.2.0 cycler-0.12.1 fonttools-4.44.3 gym-0.10.9 gym-unrealcv-1.0.0 kiwisolver-1.4.5 matplotlib-3.8.1 opencv-python-4.8.1.78 pillow-10.1.0 pyglet-2.0.10 pyparsing-3.1.1 scipy-1.11.3 unrealcv-1.0.1 wget-3.2`

```
 python .\random_agent.py -e UnrealTrack-GardenNav-DiscreteColor-v0
=> Info: Use inet client...
C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gym\envs\registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Traceback (most recent call last):
  File "D:\Unreal Projects\gym-unrealcv\example\random\random_agent.py", line 23, in <module>
    env = gym.make(args.env_id)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gym\envs\registration.py", line 167, in make
    return registry.make(id)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gym\envs\registration.py", line 119, in make
    env = spec.make()
          ^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gym\envs\registration.py", line 86, in make
    env = cls(**self._kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "d:\unreal projects\gym-unrealcv\gym_unrealcv\envs\unrealcv_tracking_1v1.py", line 55, in __init__
    self.textures_list = misc.get_textures(setting['imgs_dir'], self.docker)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\unreal projects\gym-unrealcv\gym_unrealcv\envs\utils\misc.py", line 44, in get_textures
    textures_list = os.listdir(texture_dir)
                    ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'd:\\unreal projects\\gym-unrealcv\\gym_unrealcv\\envs\\UnrealEnv\\textures'
```

**Comment by zfw1226** [comment]
Run the following command in the root to download the Texture folder: `python load_env.py -e Texture`

**Comment by iOkay** [comment]
Textures is not available to your platform (windows).

**Comment by zfw1226** [comment]
I have updated `load_end.py`. Please pull the latest version and run the command again.

**Comment by iOkay** [comment]
Thx！ It works.
